# Generated by Django 5.1.4 on 2025-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0002_remove_review_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institute_name', models.CharField(default='Decent Institute', max_length=255)),
                ('description', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='courses/default.jpg', upload_to='courses/')),
            ],
        ),
    ]
