# Generated by Django 5.1.4 on 2025-02-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(default='Full course details coming soon.'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='No short description available.'),
        ),
    ]
