# Generated by Django 5.1.4 on 2025-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0005_course_curriculum_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mode_of_learning',
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(default='Full course details coming soon.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='No short description available.'),
        ),
    ]
