# Generated by Django 5.1.4 on 2025-02-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0006_remove_course_curriculum_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key_topics',
            field=models.TextField(default='Key topics covered in this course...'),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default='Overview of the course...'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='Prerequisites or requirements for this course...'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(default='What you will learn in this course...'),
        ),
        migrations.AddField(
            model_name='course',
            name='who_can_do_this_course',
            field=models.TextField(default='Who can benefit from this course...'),
        ),
    ]
