# Generated by Django 5.1.4 on 2025-02-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0007_course_key_topics_course_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='key_topics',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='what_you_will_learn',
        ),
        migrations.RemoveField(
            model_name='course',
            name='who_can_do_this_course',
        ),
    ]
