# Generated by Django 5.1.4 on 2025-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0008_remove_course_key_topics_remove_course_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_addr',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
