# Generated by Django 5.1.4 on 2025-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentinstitute', '0010_contact_intrested_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='intrested_course',
            field=models.CharField(blank=True, choices=[('web_dev_1', 'Web Development Course - 1'), ('adv_web_tech_2', 'Advanced Web Technology Course - 2'), ('python_prog', 'Python Programming Course'), ('digital_marketing', 'Diploma in Digital Marketing'), ('data_science_powerbi', 'Data Science & Analytics with Power BI'), ('autoCAD', 'AUTOCAD'), ('tally_gst', 'Tally Prime with GST'), ('adv_excel', 'Advanced Excel'), ('financial_mgmt', 'Diploma in Financial Management'), ('cert_computer', 'Certificate Course in Computer'), ('cert_dtp', 'Certificate in DTP (Desktop Publishing)'), ('graphic_design', 'Diploma in Graphic Designing'), ('dbms', 'Database Management System (DBMS)'), ('sketchup', 'Diploma in Google SketchUp'), ('hardware_and_networking', 'Diploma Hardware & Networking'), ('acc', 'Awareness in Computer Concepts'), ('data-entry', 'Certified Data Entry Operator/Call Center Executive'), ('spoken_english', 'Spoken English Course')], max_length=50, null=True),
        ),
    ]
